/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppointmentRouteImport } from './routes/appointment'
import { Route as DoctorDashboardRouteImport } from './routes/doctor-dashboard'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SymptomAnalyzerRouteImport } from './routes/symptom-analyzer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentRoute = AppointmentRouteImport.update({
  id: '/appointment',
  path: '/appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorDashboardRoute = DoctorDashboardRouteImport.update({
  id: '/doctor-dashboard',
  path: '/doctor-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SymptomAnalyzerRoute = SymptomAnalyzerRouteImport.update({
  id: '/symptom-analyzer',
  path: '/symptom-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointment': typeof AppointmentRoute
  '/doctor-dashboard': typeof DoctorDashboardRoute
  '/doctors': typeof DoctorsRoute
  '/recovery': typeof RecoveryRoute
  '/reports': typeof ReportsRoute
  '/symptom-analyzer': typeof SymptomAnalyzerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointment': typeof AppointmentRoute
  '/doctor-dashboard': typeof DoctorDashboardRoute
  '/doctors': typeof DoctorsRoute
  '/recovery': typeof RecoveryRoute
  '/reports': typeof ReportsRoute
  '/symptom-analyzer': typeof SymptomAnalyzerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointment': typeof AppointmentRoute
  '/doctor-dashboard': typeof DoctorDashboardRoute
  '/doctors': typeof DoctorsRoute
  '/recovery': typeof RecoveryRoute
  '/reports': typeof ReportsRoute
  '/symptom-analyzer': typeof SymptomAnalyzerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointment'
    | '/doctor-dashboard'
    | '/doctors'
    | '/recovery'
    | '/reports'
    | '/symptom-analyzer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointment'
    | '/doctor-dashboard'
    | '/doctors'
    | '/recovery'
    | '/reports'
    | '/symptom-analyzer'
  id:
    | '__root__'
    | '/'
    | '/appointment'
    | '/doctor-dashboard'
    | '/doctors'
    | '/recovery'
    | '/reports'
    | '/symptom-analyzer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentRoute: typeof AppointmentRoute
  DoctorDashboardRoute: typeof DoctorDashboardRoute
  DoctorsRoute: typeof DoctorsRoute
  RecoveryRoute: typeof RecoveryRoute
  ReportsRoute: typeof ReportsRoute
  SymptomAnalyzerRoute: typeof SymptomAnalyzerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment': {
      id: '/appointment'
      path: '/appointment'
      fullPath: '/appointment'
      preLoaderRoute: typeof AppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor-dashboard': {
      id: '/doctor-dashboard'
      path: '/doctor-dashboard'
      fullPath: '/doctor-dashboard'
      preLoaderRoute: typeof DoctorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symptom-analyzer': {
      id: '/symptom-analyzer'
      path: '/symptom-analyzer'
      fullPath: '/symptom-analyzer'
      preLoaderRoute: typeof SymptomAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentRoute: AppointmentRoute,
  DoctorDashboardRoute: DoctorDashboardRoute,
  DoctorsRoute: DoctorsRoute,
  RecoveryRoute: RecoveryRoute,
  ReportsRoute: ReportsRoute,
  SymptomAnalyzerRoute: SymptomAnalyzerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
